### ISSUE TITLE
group role UI card

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-website#12]
**Is your feature request related to a problem? Please describe.**
Create group role UI card
![image](https://user-images.githubusercontent.com/33046846/82762912-642cfa00-9e21-11ea-8cb2-ddf782947678.png)

**Describe the solution you'd like**

`components/GroupDetail/GroupRole.js`
Functional component which takes in:
1. role

`components/GroupDetail/GroupRole.stories.js`
1. Initial state
1. loading state

**Comment by Nikhil-dev13** [comment]
I am working on this issue

**Comment by pratik0204** [comment]
@naveennvrgup @Nikhil-dev13  I think we can have 4 states here. 
1.Initial
2.Group state
3.Loading
3.Member state

The initial state can be "No roles to display, please select a group"
Group state can be " Role of the group "
Member State can be " Member info"

As the same component will serve two purpose here, so should we break this down to 2 more component for group and member respectively or write the logic here itself?
