### ISSUE TITLE
group permissions UI card

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-website#13]
**Is your feature request related to a problem? Please describe.**
Create group permission UI card
![image](https://user-images.githubusercontent.com/33046846/82763001-00ef9780-9e22-11ea-9c7d-2262f0cacea0.png)

**Describe the solution you'd like**

`components/GroupDetail/GroupPermissions.js`
class based component which takes in:
1.permissions dict with key(permission name) value(true/false)

`components/GroupDetail/GroupPermissions.stories.js`
1. Initial state
1. initial loading state (when the permission details are not yet arrived from backend)
1. change permission set state (on click edit we will arive here. drop down of permission_sets and save button will be present.)
1. edge case err (if the user is not admin the backend will return "You are not authorised to edit this")
1. change permission loading state (on hitting save after changing permissionset)

**Comment by rajesh6161** [comment]
@pratik0204 
Sir I want handle this issue.

**Comment by naveennvrgup** [comment]
This is assigned to u @rajesh6161

**Comment by rajesh6161** [comment]
@naveennvrgup sir 
change permission set state (on click edit we will arive here. drop down of permission_sets and save button will be present.)
why?? he will arrive on other page? can't he just manipulate the **checkbox** as it will only be clickable if he is an admin otherwise it won't be clickable anymore.

**Comment by naveennvrgup** [comment]
> why?? he will arrive on other page? can't he just manipulate the **checkbox** as it will only be clickable if he is an admin otherwise it won't be clickable anymore.
> and yes the **edit button** will also be disabled too

1. Some select members within the same group can have some special permissionset (like few executives of PR team can have the permissions to review proofs) .
1. Based on this concept we only store the default permission set of that group.
1. Admins won't be changing a few permissions but the entire permissionset.
1. If u wish we can remove the edit button and replace it with a dropdown bar and save btn on the top of this component. what say @rajesh6161?

**Comment by rajesh6161** [comment]
So I would make a different story for that solely for executives and PR team with different functionalities like dropdown. And the base will be checkbox for all admin.
What do you say sir? @naveennvrgup sir

**Comment by naveennvrgup** [comment]
i explain over call

**Comment by rajesh6161** [comment]
![UserPermissions](https://user-images.githubusercontent.com/40054161/82989474-61e0c080-a018-11ea-8d0c-866beb8c38ad.jpg)
![adminPermissions](https://user-images.githubusercontent.com/40054161/82989512-72913680-a018-11ea-968f-fa8719960f2d.jpg)
![loading](https://user-images.githubusercontent.com/40054161/82989520-74f39080-a018-11ea-81b5-17566101a850.jpg)

**Comment by rajesh6161** [comment]
@naveennvrgup  sir still ambiguity with the dropdown please help
