### ISSUE TITLE
Wireup login UI to login API

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-website#22]
**Is your feature request related to a problem? Please describe.**
As a user upon successful login I should be taken to homepage/landing page.

**Describe the solution you'd like**
1. Wire up login API to login UI
1. Setup protected routes
1. User should be taken to homepage upon successful login
1. Token received upon login should be stored in local storage.

**Additional context**
1. Create a login page component (at `pages/Auth/LoginPage.js`) that just centers login form component on the screen. (we can do fancy stuff later).
1. Make the login page as the first-page user see when he is logged out.
1. If the user is logged in they should be automatically redirected into homepage when they visit the site.
1. You can use the method suggested by @kaushik27mishra as to follow the pattern use here https://github.com/flatlogic/react-material-admin. Or you can come up with your own pattern. We can debate on the result in the PR.

**Comment by naveennvrgup** [comment]
Since no updates have been submitted by @kaushik27mishra I am taking over this issue.

**Comment by kaushik27mishra** [comment]
I am working on it, sir! I have setup the basic routes and private and public routes. I am a little confused regarding handling the different user types using React Context. So I haven't made any update yet! and I was busy for a few days in between.
