### ISSUE TITLE
Reusable error component 

### ISSUE THREAD

**Issue by pratik0204** [ECellNitrr/teesco-website#24]
**Is your feature request related to a problem? Please describe.**
Make an error component, displayed if any api calls throws an error.
![Screenshot from 2020-06-02 21-46-42](https://user-images.githubusercontent.com/46794833/83547977-a68cc000-a520-11ea-927f-bd8f96880735.png)

**Describe the solution you'd like**

`components/Widgets/Error/Error.js`

A functional component which takes width as prop, to make it fit in every container component.

`components/Widgets/Error/Error.stories.js`

Just an initial state, with error.

**Comment by Nikhil-dev13** [comment]
I will like to work on this issue

**Comment by pratik0204** [comment]
@Nikhil-dev13 you are assigned with this issue.
