### ISSUE TITLE
Component to search organisation UI/UX

### ISSUE THREAD

**Issue by kaushik27mishra** [ECellNitrr/teesco-website#33]
**Is your feature request related to a problem? Please describe.**
A component for the user to search for organisations.

**Describe the solution you'd like**
`components/organisation/searchOrg.js`
A class-based component with a search box which takes in an array of objects (organisations and their ids).

It has three states.
`components/organisation/searchOrg.stories.js`
1) Initial state
2) loading state
3) Search State
4) Error state( In case the length of the array is 0 it shows "No Organisation found".)

**Additional context**
![Screenshot from 2020-06-11 08-23-19](https://user-images.githubusercontent.com/43887027/84339893-0fc5a080-abbd-11ea-91b9-f5b70c767b30.png)

**Comment by Nikhil-dev13** [comment]
i would like to work on this
