### ISSUE TITLE
login form component

### ISSUE THREAD

**Issue by naveennvrgup** [ECellNitrr/teesco-website#7]
**Is your feature request related to a problem? Please describe.**
We need a login form UI

**Describe the solution you'd like**
1. Create a login form component `src/components/Login/LoginForm.js`
1. Write stories for following states at `src/components/Login/LoginForm.stories.js`:
    1. Initial state
    1. Loading during api call
    1. Error state - due to wrong input
    1. Special case error messages like
![image](https://user-images.githubusercontent.com/33046846/82723786-fa143800-9cee-11ea-97c8-dad45509fa6c.png)

**Comment by kaushik27mishra** [comment]
Shall we setup the auth setup in redux and public-private routes before making the login form? Let me know what do you think!

**Comment by naveennvrgup** [comment]
Yup We have to create a separate issue for that route setup but it wont affect the UI creation.

**Comment by naveennvrgup** [comment]
We will have a detailed discussion about that in the today's meeting.

**Comment by naveennvrgup** [comment]
I am working on this
